# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-31 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dname', models.CharField(choices=[('1', '销售部'), ('2', '采购部'), ('3', '信息技术部'), ('4', '客服部'), ('5', '市场部'), ('6', '事业加盟部'), ('7', '战略研究部'), ('8', '人事新政部'), ('9', '财务部'), ('9', '仓储配送部')], max_length=2)),
                ('Atype', models.CharField(max_length=50)),
                ('Zcbh', models.CharField(max_length=30)),
                ('Bgr', models.CharField(max_length=30)),
                ('Brand', models.CharField(max_length=200)),
                ('Aunit', models.CharField(max_length=10)),
                ('Count', models.IntegerField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Status', models.BooleanField(default=True)),
                ('gtime', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('memo', models.TextField()),
            ],
        ),
    ]
