# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-31 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apiorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apiname', models.CharField(max_length=50)),
                ('worder', models.CharField(max_length=10)),
                ('horder', models.CharField(max_length=10)),
                ('yorder', models.CharField(max_length=10)),
                ('product', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dname', models.CharField(choices=[('1', '销售部'), ('2', '采购部'), ('3', '信息技术部'), ('4', '客服部'), ('5', '市场部'), ('6', '事业加盟部'), ('7', '战略研究部'), ('8', '人事行政部'), ('9', '财务部'), ('10', '仓储配送部')], max_length=2)),
                ('Atype', models.CharField(choices=[('1', '笔记本电脑'), ('2', 'MOTO无线基站'), ('3', 'UPS电源'), ('4', '标签打印机'), ('5', '传真机'), ('6', '打印机'), ('7', '大型存储设备'), ('8', '服务器'), ('9', '服务器机柜'), ('10', '交换机'), ('11', '扫描枪'), ('12', '扫描仪'), ('13', '台式电脑'), ('14', '条码打印机'), ('15', '投影仪'), ('16', '投影仪幕布'), ('17', '网络设备'), ('18', '无动力筒机'), ('19', '显示器'), ('20', '针式打印机')], max_length=2)),
                ('Status', models.CharField(choices=[('1', '在用'), ('0', '闲置')], max_length=2)),
                ('Zcbh', models.CharField(max_length=30)),
                ('Bgr', models.CharField(max_length=30)),
                ('Brand', models.CharField(max_length=200)),
                ('Aunit', models.CharField(max_length=10)),
                ('Count', models.IntegerField()),
                ('Price', models.FloatField()),
                ('gtime', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Asset_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Aunit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
