# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-12 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Zcbh', models.CharField(max_length=30)),
                ('Bgr', models.CharField(max_length=30)),
                ('Brand', models.CharField(max_length=200)),
                ('Count', models.IntegerField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Status', models.BooleanField(default=True)),
                ('gtime', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Asset_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Aunit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='Atype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AssetType', to='app01.AssetType'),
        ),
        migrations.AddField(
            model_name='asset',
            name='Aunit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='app01.Aunit'),
        ),
        migrations.AddField(
            model_name='asset',
            name='Dname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept', to='app01.dept'),
        ),
    ]
