# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-12 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='Atype',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='Aunit',
            field=models.CharField(max_length=10),
        ),
    ]
