# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-31 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20161231_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='Atype',
            field=models.CharField(choices=[('1', '笔记本电脑'), ('2', 'MOTO无线基站'), ('3', 'UPS电源'), ('4', '标签打印机'), ('5', '传真机'), ('6', '打印机'), ('7', '大型存储设备'), ('8', '服务器'), ('9', '服务器机柜'), ('10', '交换机'), ('11', '扫描枪'), ('12', '扫描仪'), ('13', '台式电脑'), ('14', '条码打印机'), ('15', '投影仪'), ('16', '投影仪幕布'), ('17', '网络设备'), ('18', '无动力筒机'), ('19', '显示器'), ('20', '针式打印机')], max_length=2),
        ),
    ]
