# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-13 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20170104_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='Dname',
            field=models.CharField(choices=[('1', '销售部'), ('2', '采购部'), ('3', '信息技术部'), ('4', '客服部'), ('5', '市场部'), ('6', '事业加盟部'), ('7', '战略研究部'), ('8', '人事行政部'), ('9', '财务部'), ('10', '仓储配送部')], max_length=2),
        ),
        migrations.AlterField(
            model_name='asset',
            name='Status',
            field=models.CharField(choices=[('1', '在用'), ('0', '闲置')], max_length=2),
        ),
    ]
