# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-17 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20170213_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='Price',
            field=models.FloatField(),
        ),
    ]
